<?php
/** Actual protocol classes in the real WordPress fixture; synthetic payload edge cases. */
use GetMCP\Remote\McpClient as Client;
use GetMCP\Remote\HeaderSchema;
use GetMCP\Remote\SafeHttp;

$checks = array(); $assert = function( $ok, $name ) use ( &$checks ) { $checks[ $name ] = (bool) $ok; if ( ! $ok ) { throw new RuntimeException( $name ); } };
$reject = function( $callback, $name ) use ( $assert ) { try { $callback(); } catch ( Throwable $e ) { $assert( true, $name ); return; } $assert( false, $name ); };
$json = '{"jsonrpc":"2.0","id":"id-a","result":{"content":[],"structuredContent":{"empty":{},"list":[]}}}';
$result = Client::decode( $json, 'application/json; charset=UTF-8', 'id-a' );
$assert( $result['result']['structuredContent']['empty'] instanceof stdClass && is_array( $result['result']['structuredContent']['list'] ), 'objects_and_arrays_not_conflated' );
$assert( Client::decode( ': heartbeat' . "\r\r" . 'event: message' . "\rdata: " . $json . "\r\r", 'text/event-stream', 'id-a' )['id'] === 'id-a', 'cr_only_sse_frames_supported' );
$multiline = 'data: {"jsonrpc":"2.0",' . "\ndata: \"id\":\"id-a\",\"result\":{}}\n\n";
$assert( Client::decode( $multiline, 'text/event-stream', 'id-a' )['result'] instanceof stdClass, 'multiline_sse_data_supported' );
$reject( fn() => Client::decode( '{broken', 'application/json', 'id-a' ), 'malformed_json_denied' );
$reject( fn() => Client::decode( $json, 'text/plain', 'id-a' ), 'unsupported_content_type_denied' );
$reject( fn() => Client::decode( $json, 'application/json', 'other-id' ), 'mismatched_response_id_denied' );
$reject( fn() => Client::decode( 'data: ' . $json . "\n\ndata: " . $json . "\n\n", 'text/event-stream', 'id-a' ), 'duplicate_sse_response_denied' );
$reject( fn() => Client::decode( '{"jsonrpc":"2.0","id":"id-a","result":{},"error":{"code":-1}}', 'application/json', 'id-a' ), 'ambiguous_result_error_denied' );
$reject( fn() => Client::decode( 'data: {"jsonrpc":"2.0","id":"server-id","method":"sampling/createMessage","params":{}}' . "\n\n", 'text/event-stream', 'id-a' ), 'server_client_interaction_denied' );
$assert( Client::header_value( ' padded ' ) === '=?base64?IHBhZGRlZCA=?=', 'header_whitespace_sentinel_encoded' );
$assert( Client::header_value( "one\ntwo" ) === '=?base64?' . base64_encode( "one\ntwo" ) . '?=', 'header_newline_sentinel_encoded' );
$assert( Client::header_value( '=?base64?literal?=' ) !== '=?base64?literal?=', 'header_sentinel_ambiguity_avoided' );
$schema = array( 'type' => 'object', 'properties' => array( 'account' => array( 'type' => 'object', 'properties' => array( 'region' => array( 'type' => 'string', 'x-mcp-header' => 'Region' ), 'active' => array( 'type' => 'boolean', 'x-mcp-header' => 'Active' ) ) ) ) );
$headers = HeaderSchema::headers( $schema, array( 'account' => array( 'region' => 'us-west1', 'active' => false ) ) );
$assert( $headers === array( 'Mcp-Param-Region' => 'us-west1', 'Mcp-Param-Active' => 'false' ), 'nested_header_properties_mirrored' );
$assert( HeaderSchema::headers( $schema, array() ) === array(), 'absent_header_parameters_omitted' );
$reject( fn() => HeaderSchema::headers( $schema, array( 'account' => array( 'active' => 'false' ) ) ), 'header_primitive_type_enforced' );
$invalid = $schema; $invalid['properties']['account']['properties']['active']['x-mcp-header'] = 'region';
$reject( fn() => HeaderSchema::paths( $invalid ), 'case_insensitive_duplicate_header_annotations_denied' );
$reject( fn() => HeaderSchema::paths( array( 'oneOf' => array( array( 'type' => 'string', 'x-mcp-header' => 'Bad' ) ) ) ), 'unreachable_header_annotation_denied' );
$reject( fn() => SafeHttp::validate_headers( array( 'Cookie' => 'fixture' ) ), 'upstream_cookie_header_denied' );
$reject( fn() => SafeHttp::validate_url( 'https://example.org/path#fragment' ), 'endpoint_fragment_denied' );
$reject( fn() => SafeHttp::validate_url( 'https://user:pass@example.org/path' ), 'url_credentials_denied' );
$s = new \GetMCP\Core\Server( array( 'id' => 99991, 'uuid' => 'fixture-server', 'server_kind' => 'remote-mcp', 'settings' => wp_json_encode( array( 'remote_mcp' => array( 'endpoint' => 'https://example.org/getmcp-qa/json', 'auth_mode' => 'none' ) ) ) ) );
$key = new ReflectionProperty( Client::class, 'key' );
$assert( $key->getValue( new Client( $s, 2, 100 ) ) !== $key->getValue( new Client( $s, 3, 100 ) ), 'upstream_cache_and_session_user_isolation' );
$assert( $key->getValue( new Client( $s, 2, 100 ) ) !== $key->getValue( new Client( $s, 2, 101 ) ), 'upstream_cache_and_session_gateway_isolation' );
$different = clone $s; $different->outbound_auth_credentials = 'different-fixture-identity';
$assert( $key->getValue( new Client( $s, 2, 100 ) ) !== $key->getValue( new Client( $different, 2, 100 ) ), 'credential_change_invalidates_upstream_cache_and_session' );
$headers_calls = 0;
$hook = function( $response, $args, $url ) use ( &$headers_calls ) { if ( str_contains( $url, '/getmcp-qa/timeout' ) ) { ++$headers_calls; return new WP_Error( 'http_request_failed', 'fixture timeout' ); } return $response; };
add_filter( 'pre_http_request', $hook, 1, 3 );
$reject( fn() => SafeHttp::request( 'https://example.org/getmcp-qa/timeout', 'POST', array(), '{}' ), 'timeout_reported_without_transport_retry' );
remove_filter( 'pre_http_request', $hook, 1 ); $assert( $headers_calls === 1, 'timeout_single_http_attempt' );
$redirect = fn( $response, $args, $url ) => str_contains( $url, '/getmcp-qa/redirect' ) ? array( 'response' => array( 'code' => 302 ), 'body' => '', 'headers' => array( 'location' => 'https://private.invalid/' ) ) : $response;
add_filter( 'pre_http_request', $redirect, 1, 3 );
$reject( fn() => SafeHttp::request( 'https://example.org/getmcp-qa/redirect' ), 'redirect_refused_without_forwarding_credentials' ); remove_filter( 'pre_http_request', $redirect, 1 );
echo wp_json_encode( array( 'passed' => count( $checks ), 'checks' => $checks, 'coverage' => 'Actual classes inside WordPress; edge-case payloads and fault injection use fixtures.' ), JSON_PRETTY_PRINT );
