<?php
/** Execute with wp eval-file inside the owned Docker fixture. Real WordPress/database/HTTP. */
use GetMCP\Gateway\FeatureManager as FM;
use GetMCP\Gateway\FeatureHandler as FH;
use GetMCP\Remote\McpClient;
use GetMCP\Remote\UpstreamOAuth;
use GetMCP\Remote\UpstreamConnections as UC;
use GetMCP\Auth\FirstPartyOAuth as FO;
use GetMCP\Core\ServerManager as SM;

global $wpdb;
$checks = array();
$assert = function( $ok, $name ) use ( &$checks ) { $checks[ $name ] = (bool) $ok; if ( ! $ok ) { throw new RuntimeException( 'FAIL: ' . $name ); } };
$reject = function( $callback, $name ) use ( $assert ) { try { $callback(); } catch ( Throwable $e ) { $assert( true, $name ); return; } $assert( false, $name ); };
wp_set_current_user( 1 );
$a = username_exists( 'qa-user-a' ) ?: wp_create_user( 'qa-user-a', 'getmcp-fixture-only', 'qa-a@example.invalid' );
$b = username_exists( 'qa-user-b' ) ?: wp_create_user( 'qa-user-b', 'getmcp-fixture-only', 'qa-b@example.invalid' );
$prefix = 'QA ' . substr( wp_generate_uuid4(), 0, 6 ) . ' ';
$remote = function( $suffix, $auth = 'none', $extra = array() ) use ( $prefix, $a ) {
	return FM::run( 'save', array_merge( array( 'kind' => 'remote-mcp', 'name' => $prefix . $suffix, 'allowed_user_ids' => array( 1, (int) $a ), 'remote' => array( 'endpoint' => 'https://example.org/getmcp-qa/' . $suffix, 'auth_mode' => $auth ) ), $extra ) );
};
$json = $remote( 'json', 'shared', array( 'credentials' => array( 'headers' => array( 'Authorization' => 'Bearer fixture-shared' ) ) ) );
$sse = $remote( 'sse' ); $legacy = $remote( 'legacy' ); $pages = $remote( 'pages' );
$g1 = FM::run( 'save', array( 'kind' => 'gateway', 'name' => $prefix . 'Project A', 'allowed_user_ids' => array( 1, (int) $a ), 'server_ids' => array( $json['id'], $sse['id'] ) ) );
$g2 = FM::run( 'save', array( 'kind' => 'gateway', 'name' => $prefix . 'Project B', 'allowed_user_ids' => array( (int) $b ), 'server_ids' => array( $legacy['id'] ) ) );
$server = fn( $id ) => ( new SM() )->get( $id );
$assert( $server( $g1['id'] )->server_kind === 'gateway' && $g1['id'] > 0, 'persisted_positive_gateway_identity' );
$assert( FO::can_user_access( (int) $a, $server( $g1['id'] ) ) && ! FO::can_user_access( (int) $b, $server( $g1['id'] ) ), 'separate_gateway_users' );
$assert( ! FO::can_user_access( 1, $server( $g2['id'] ) ), 'excluded_administrator_denied' );
$reject( fn() => FM::run( 'save', array( 'name' => 'Forbidden', 'kind' => 'gateway' ), (int) $a ), 'subscriber_cannot_manage' );
$reject( fn() => FM::run( 'save', array( 'name' => 'Nested', 'kind' => 'gateway', 'server_ids' => array( $g1['id'] ) ) ), 'nested_gateway_rejected' );
$reject( fn() => \GetMCP\Remote\SafeHttp::validate_url( 'https://127.0.0.1/private' ), 'private_https_rejected' );
$reject( fn() => \GetMCP\Remote\SafeHttp::validate_url( 'http://example.org/mcp' ), 'plain_http_rejected' );
$reject( fn() => \GetMCP\Remote\SafeHttp::validate_headers( array( 'Authorization' => "Bearer x\r\nX-Injected: 1" ) ), 'header_injection_rejected' );
$assert( ! str_contains( wp_json_encode( FM::run( 'get', array( 'id' => $json['id'] ) ) ), 'fixture-shared' ), 'management_export_secret_free' );
$assert( ! str_contains( $server( $json['id'] )->outbound_auth_credentials, 'fixture-shared' ), 'shared_secret_encrypted_at_rest' );
$hj = new FH( $server( $g1['id'] ), null, (int) $a );
$tools = $hj->handle( 'tools/list', array() )['tools'];
$assert( count( $tools ) === 2 && $tools[0]['name'] !== $tools[1]['name'], 'duplicate_upstream_names_namespaced' );
$assert( $tools[0]['inputSchema']['properties'] instanceof stdClass, 'empty_schema_object_preserved' );
$call = $hj->handle( 'tools/call', array( 'name' => $tools[0]['name'], 'arguments' => array() ) );
$assert( $call['structuredContent']['identity'] === 'Bearer fixture-shared', 'only_operator_credential_forwarded' );
$assert( $call['structuredContent']['empty'] instanceof stdClass && $call['structuredContent']['uri'] === 'fixture://opaque', 'structured_result_preserved' );
$assert( str_starts_with( $call['content'][1]['uri'], 'getmcp://' ), 'embedded_resource_link_rewritten' );
$error = $hj->handle( 'tools/call', array( 'name' => $tools[1]['name'], 'arguments' => array( 'fail' => true ) ) );
$assert( $error['isError'] === true && count( $error['content'] ) === 2, 'sse_tool_error_content_preserved' );
$resources = $hj->handle( 'resources/list', array() )['resources'];
$assert( count( $resources ) === 2 && $resources[0]['uri'] !== $resources[1]['uri'], 'duplicate_resource_uris_namespaced' );
$read = $hj->handle( 'resources/read', array( 'uri' => $resources[0]['uri'] ) );
$assert( $read['contents'][0]['uri'] === $resources[0]['uri'], 'gateway_resource_routing_reversible' );
$templates = $hj->handle( 'resources/templates/list', array() )['resourceTemplates'];
$assert( str_contains( $templates[0]['uriTemplate'], '{id}{?filter}' ), 'resource_template_expressions_preserved' );
$expanded = str_replace( array( '{id}', '{?filter}' ), array( '42', '?filter=a' ), $templates[0]['uriTemplate'] );
$assert( $hj->handle( 'resources/read', array( 'uri' => $expanded ) )['contents'][0]['uri'] === $expanded, 'expanded_resource_template_routed' );
$prompts = $hj->handle( 'prompts/list', array() )['prompts'];
$assert( $prompts[0]['arguments'][0]['required'] === true, 'prompt_argument_schema_preserved' );
$assert( $hj->handle( 'prompts/get', array( 'name' => $prompts[0]['name'], 'arguments' => array( 'person' => 'QA' ) ) )['messages'][0]['content']['text'] === 'Hello QA', 'prompt_get_routed' );
$assert( count( ( new FH( $server( $legacy['id'] ), null, 1 ) )->handle( 'tools/list', array() )['tools'] ) === 1, 'legacy_initialize_session_version_negotiated' );
$hp = new FH( $server( $pages['id'] ), null, 1 );
$first = $hp->handle( 'tools/list', array() ); $second = $hp->handle( 'tools/list', array( 'cursor' => $first['nextCursor'] ) );
$assert( count( $first['tools'] ) === 100 && count( $second['tools'] ) === 100, 'upstream_and_gateway_pagination' );
$reject( fn() => $hp->handle( 'tools/list', array( 'cursor' => $first['nextCursor'] . 'x' ) ), 'forged_cursor_rejected' );
foreach ( array( 'malformed', 'outage', 'duplicate' ) as $case ) { $r = $remote( $case ); $reject( fn() => ( new FH( $server( $r['id'] ), null, 1 ) )->handle( 'tools/list', array() ), $case . '_rejected' ); }
// Direct-server allowlists do not restrict delegated gateway capabilities.
FM::run( 'save', array( 'id' => $json['id'], 'allowed_user_ids' => array() ) );
$assert( ! FO::can_user_access( (int) $a, $server( $json['id'] ) ), 'direct_access_denied' );
$assert( count( $hj->handle( 'tools/list', array() )['tools'] ) === 2, 'gateway_delegation_overrides_direct_allowlist' );
FM::run( 'save', array( 'id' => $g1['id'], 'server_ids' => array( $sse['id'] ) ) );
$reject( fn() => $hj->handle( 'tools/call', array( 'name' => $tools[0]['name'] ) ), 'removed_member_stops_calls_immediately' );
FM::run( 'save', array( 'id' => $g1['id'], 'server_ids' => array( $json['id'], $sse['id'] ) ) );
FM::run( 'save', array( 'id' => $sse['id'], 'status' => 'paused' ) );
$reject( fn() => $hj->handle( 'resources/read', array( 'uri' => $resources[1]['uri'] ) ), 'paused_member_stops_resource_reads' );
FM::run( 'save', array( 'id' => $sse['id'], 'status' => 'active' ) );
// Two upstream OAuth grants with independent accounts and refreshes.
$oauth = $remote( 'oauth', 'oauth', array( 'allowed_user_ids' => array( 1, (int) $a, (int) $b ), 'remote' => array( 'endpoint' => 'https://example.org/getmcp-qa/oauth', 'auth_mode' => 'oauth', 'client_id' => 'fixture-client' ) ) );
$complete = function( $user, $account ) use ( $oauth, $server ) { $begin = UpstreamOAuth::begin( $server( $oauth['id'] ), $user ); parse_str( wp_parse_url( $begin['authorization_url'], PHP_URL_QUERY ), $query ); $query['code'] = $account; $query['iss'] = 'https://example.org/getmcp-qa/issuer'; UpstreamOAuth::complete( $query, $user ); return $query; };
$query = $complete( (int) $a, 'account-a' ); $complete( (int) $b, 'account-b' );
$reject( fn() => UpstreamOAuth::complete( $query, (int) $a ), 'oauth_callback_replay_rejected' );
$ra = ( new FH( $server( $oauth['id'] ), null, (int) $a ) )->handle( 'tools/call', array( 'name' => 'echo' ) );
$rb = ( new FH( $server( $oauth['id'] ), null, (int) $b ) )->handle( 'tools/call', array( 'name' => 'echo' ) );
$assert( $ra['structuredContent']['identity'] !== $rb['structuredContent']['identity'], 'two_user_oauth_account_isolation' );
$grant = UC::get( $oauth['id'], (int) $a ); $old = $grant['version']; $grant['data']['expires_at'] = 0; UC::save( $oauth['id'], (int) $a, $grant['data'], $old );
UC::headers( $server( $oauth['id'] ), (int) $a );
$assert( UC::get( $oauth['id'], (int) $a )['data']['expires_at'] > time(), 'upstream_refresh_rotates_grant' );
$begin = UpstreamOAuth::begin( $server( $oauth['id'] ), (int) $a ); parse_str( wp_parse_url( $begin['authorization_url'], PHP_URL_QUERY ), $pending );
UC::disconnect( $oauth['id'], (int) $a ); $pending['code'] = 'account-a'; $pending['iss'] = 'https://example.org/getmcp-qa/issuer';
$reject( fn() => UpstreamOAuth::complete( $pending, (int) $a ), 'disconnect_cancels_pending_callback' );
$reject( fn() => UC::headers( $server( $oauth['id'] ), (int) $a ), 'disconnect_no_shared_fallback' );
$assert( UC::get( $oauth['id'], (int) $b ) !== null, 'disconnect_preserves_other_user_grant' );
$complete( (int) $a, 'account-a' );
$assert( UC::get( $oauth['id'], (int) $a ) !== null, 'reconnect_after_disconnect_uses_tombstone_version' );
$reject( fn() => UC::save( $oauth['id'], (int) $a, array( 'access_token' => 'stale-fixture' ) ), 'initial_insert_cannot_replace_existing_grant' );
$assert( ! str_contains( wp_json_encode( FM::run( 'list', array() ) ), 'access-account' ), 'oauth_grants_absent_from_management_exports' );
$assert( $wpdb->get_var( "SELECT COUNT(*) FROM {$wpdb->prefix}getmcp_call_logs WHERE method='tools/call'" ) > 0, 'remote_tool_calls_logged' );
// Existing native servers, encrypted credentials, and the original gateway remain independent.
$native = ( new SM() )->create( array( 'name' => $prefix . 'Native', 'auth_type' => 'oauth', 'auth_config' => wp_json_encode( array( 'provider' => 'getmcp', 'allowed_user_ids' => array() ) ), 'outbound_auth_type' => 'bearer', 'outbound_auth_credentials' => wp_json_encode( array( 'token' => 'fixture-native-secret' ) ) ) );
$encrypted = $native->outbound_auth_credentials;
$resource = ( new \GetMCP\Core\ResourceManager() )->create( array( 'server_id' => $native->id, 'uri' => 'native://readme', 'name' => 'Readme', 'data_source_config' => wp_json_encode( array( 'content' => 'Native content preserved' ) ) ) );
$prompt = ( new \GetMCP\Core\PromptManager() )->create( array( 'server_id' => $native->id, 'name' => 'native-greeting', 'template_content' => 'Hello {{person}}', 'arguments' => wp_json_encode( array( array( 'name' => 'person', 'required' => true ) ) ) ) );
$tool = ( new \GetMCP\Core\ToolManager() )->create( array( 'server_id' => $native->id, 'name' => 'native-echo', 'slug' => 'native-echo', 'http_method' => 'POST', 'endpoint_url' => 'https://example.org/getmcp-qa/json', 'input_schema' => array( 'type' => 'object', 'properties' => new stdClass() ), 'body_template' => wp_json_encode( array( 'jsonrpc' => '2.0', 'id' => 'native', 'method' => 'tools/call', 'params' => array( 'name' => 'echo' ) ) ) ) );
$native_gateway = FM::run( 'save', array( 'kind' => 'gateway', 'name' => $prefix . 'Native delegated', 'allowed_user_ids' => array( 1 ), 'server_ids' => array( $native->id ) ) );
$hn = new FH( $server( $native_gateway['id'] ), null, 1 );
$native_tools = $hn->handle( 'tools/list', array() )['tools'];
$assert( count( $native_tools ) === 1 && $native->server_kind === 'native', 'native_server_default_and_tool_aggregation' );
$assert( ! empty( $hn->handle( 'tools/call', array( 'name' => $native_tools[0]['name'] ) )['content'] ), 'native_tool_executor_delegated' );
$native_resources = $hn->handle( 'resources/list', array() )['resources'];
$assert( $hn->handle( 'resources/read', array( 'uri' => $native_resources[0]['uri'] ) )['contents'][0]['text'] === 'Native content preserved', 'native_resource_delegated' );
$native_prompts = $hn->handle( 'prompts/list', array() )['prompts'];
$assert( str_contains( $hn->handle( 'prompts/get', array( 'name' => $native_prompts[0]['name'], 'arguments' => array( 'person' => 'QA' ) ) )['messages'][0]['content']['text'], 'QA' ), 'native_prompt_delegated' );
$assert( $server( $native->id )->outbound_auth_credentials === $encrypted, 'existing_native_credential_preserved' );
$incoming = array( 'url' => 'https://example.org/getmcp-qa/json', 'headers' => array( 'Authorization' => 'Bearer gateway-fixture' ) );
$passthrough = new \GetMCP\Core\Server( array( 'auth_type' => 'bearer' ) );
$_SERVER['HTTP_AUTHORIZATION'] = 'Bearer gateway-fixture';
$isolated = \GetMCP\Gateway\Delegation::run( fn() => ( new \GetMCP\Execution\AuthInjector() )->inject( $incoming, false, $passthrough ) );
$assert( ! isset( $isolated['headers']['Authorization'] ) && $_SERVER['HTTP_AUTHORIZATION'] === 'Bearer gateway-fixture', 'native_delegate_never_forwards_gateway_bearer_and_restores_context' );
unset( $_SERVER['HTTP_AUTHORIZATION'] );
$reject( fn() => ( new SM() )->update( $g1['id'], array( 'server_kind' => 'native', 'auth_type' => 'none' ) ), 'gateway_kind_and_auth_downgrade_rejected' );
$manifest = \GetMCP\Core\ServerTransfer::export( $server( $oauth['id'] ) );
$assert( $manifest['format'] === 'getmcp/connections-v1' && ! str_contains( wp_json_encode( $manifest ), 'access-account' ) && ! str_contains( wp_json_encode( $manifest ), 'refresh-account' ), 'whole_server_export_excludes_upstream_grants' );
$legacy_url = \GetMCP\Gateway\McpGateway::server()->get_endpoint_url();
$assert( $legacy_url === home_url( '/mcp' ), 'original_gateway_endpoint_preserved' );
$old_enabled = \GetMCP\Gateway\McpGateway::is_enabled(); $old_mode = \GetMCP\Gateway\McpGateway::mode();
\GetMCP\Gateway\McpGateway::set_enabled( true ); \GetMCP\Gateway\McpGateway::set_mode( 'all' );
$members = \GetMCP\Gateway\McpGateway::included_servers();
$assert( in_array( $native->id, array_map( fn( $s ) => $s->id, $members ), true ) && ! in_array( $json['id'], array_map( fn( $s ) => $s->id, $members ), true ), 'original_gateway_native_preserved_remote_opt_in' );
FM::run( 'save', array( 'id' => $json['id'], 'remote' => array_merge( $json['remote'], array( 'publish_original' => true ) ) ) );
$members = \GetMCP\Gateway\McpGateway::included_servers();
$assert( in_array( $json['id'], array_map( fn( $s ) => $s->id, $members ), true ) && ! in_array( $g1['id'], array_map( fn( $s ) => $s->id, $members ), true ), 'original_gateway_explicit_publication_excludes_nested_gateways' );
\GetMCP\Gateway\McpGateway::set_enabled( $old_enabled ); \GetMCP\Gateway\McpGateway::set_mode( $old_mode );
FM::run( 'save', array( 'id' => $oauth['id'], 'remote' => array_merge( $oauth['remote'], array( 'scope' => 'changed' ) ) ) );
$reject( fn() => UC::headers( $server( $oauth['id'] ), (int) $b ), 'configuration_change_invalidates_user_grant' );
FM::run( 'delete', array( 'id' => $oauth['id'] ) );
$assert( UC::get( $oauth['id'], (int) $b ) === null, 'server_deletion_cleans_user_grants' );
$license = $GLOBALS['getmcp_license'];
$GLOBALS['getmcp_license'] = new class { public function get_status() { return 'not_connected'; } public function get_license_data() { return array(); } };
\GetMCP\Licensing\LicenseTier::clear_cache();
$reject( fn() => FM::run( 'save', array( 'name' => 'Unlicensed gateway fixture', 'kind' => 'gateway' ) ), 'unlicensed_feature_creation_denied' );
$GLOBALS['getmcp_license'] = $license; \GetMCP\Licensing\LicenseTier::clear_cache();
echo wp_json_encode( array( 'passed' => count( $checks ), 'checks' => $checks, 'fixture' => array( 'gateway_a' => $g1['id'], 'gateway_b' => $g2['id'], 'user_a' => $a, 'user_b' => $b ), 'limitations' => array( 'License provider is a test double.', 'Upstream requests use an owned HTTP fixture mapped after production URL validation. TLS handshake and real provider consent are unverified.' ) ), JSON_PRETTY_PRINT );
