<?php
/** Owned fixture only: real schema, switches, permission checks and isolation. */
use GetMCPExtensions\Runtime as R;
use GetMCP\Gateway\FeatureManager as F;
use GetMCP\Core\ServerManager as S;
wp_set_current_user( 1 );
global $wpdb;
$checks=array();$assert=function($ok,$name)use(&$checks){$checks[$name]=(bool)$ok;if(!$ok)throw new RuntimeException($name);};
$assert( R::ready() && in_array(R::status()['profile'],array('vendor-1.6.0','vendor-original-1.6.0','vendor-original-1.7.0'),true),'untouched_vendor_profile_and_early_adapter_loaded' );
if ( 'vendor-original-1.7.0' === R::status()['profile'] ) { $assert( str_contains( (new ReflectionClass( GetMCP\Api\ServersController::class ))->getFileName(), '/compat/versions/1.7.0/' ), 'getmcp_1_7_controller_adapter_loaded' ); $assert( str_contains( (new ReflectionClass( GetMCP\Execution\ToolExecutor::class ))->getFileName(), '/compat/versions/1.7.0/' ), 'getmcp_1_7_ftp_executor_adapter_loaded' ); }
$ref=new ReflectionClass( S::class );$assert(str_contains($ref->getFileName(),'/getmcp-extensions/compat/'),'adapter_loaded_from_separate_plugin');
$assert(is_file(WPMU_PLUGIN_DIR.'/getmcp-extensions-guard.php'),'persistent_guard_installed');
$expected_db = 'vendor-original-1.7.0' === R::status()['profile'] ? '1.26' : '1.25';
$assert(GETMCP_DB_VERSION===$expected_db && get_option('getmcp_extensions_schema_version')==='1','independent_schema_version_leaves_vendor_version_unchanged');
$before=$wpdb->get_results("SELECT id,auth_config,outbound_auth_credentials,settings,status FROM {$wpdb->prefix}getmcp_servers ORDER BY id",ARRAY_A);
$remote=F::run('save',array('kind'=>'remote-mcp','name'=>'Addon module fixture','allowed_user_ids'=>array(1),'remote'=>array('endpoint'=>'https://example.org/getmcp-qa/json','auth_mode'=>'shared','publish_original'=>true),'credentials'=>array('headers'=>array('Authorization'=>'Bearer fixture-add-on'))));
$gateway=F::run('save',array('kind'=>'gateway','name'=>'Addon native gateway','allowed_user_ids'=>array(1),'server_ids'=>array($remote['id'])));
$manager=new S();$server=$manager->get($remote['id']);$credentials=$server->outbound_auth_credentials;
$default=R::settings();$disabled=$default;$disabled['features']['remote_mcp']=false;
$assert(!is_wp_error(R::save($disabled)),'remote_module_disable_saved');
$assert(!R::server_enabled($server)&&R::server_enabled($manager->get($gateway['id'])),'independent_remote_and_gateway_switches');
$assert(!getmcp_extensions_guard_row((object)array('server_kind'=>'native','auth_type'=>'none')),'unmanaged_native_endpoint_unaffected');
$assert(getmcp_extensions_guard_row((object)$server->to_array()),'disabled_remote_guard_denies_endpoint');
$assert(!\GetMCP\Auth\FirstPartyOAuth::can_user_access(1,$server),'disabled_remote_refuses_native_oauth');
$assert(count(\GetMCP\Gateway\ProjectGateway::members($manager->get($gateway['id'])))===0,'disabled_remote_removed_from_gateway_members');
$assert(!in_array($remote['id'],array_column(array_map(fn($s)=>array('id'=>$s->id),\GetMCP\Gateway\McpGateway::included_servers()),'id'),true),'disabled_remote_removed_from_original_gateway');
try { F::run('preview',array('id'=>$remote['id']));$blocked=false; }catch(Throwable $e){$blocked=true;}$assert($blocked,'disabled_remote_preview_denied');
$assert(is_wp_error(R::save($default)),'stale_module_update_rejected');
$settings=R::settings();$settings['features']['native_oauth']=false;
$assert(is_wp_error(R::save($settings)),'oauth_dependency_enforced');
$settings=R::settings();$settings['features']['project_gateways']=false;
$assert(!is_wp_error(R::save($settings))&&!R::server_enabled($manager->get($gateway['id'])),'gateway_module_disable_saved');
$settings=R::settings();$settings['features']=array('native_oauth'=>false,'remote_mcp'=>false,'project_gateways'=>false);R::save($settings);
$assert(!R::enabled('native_oauth'),'native_oauth_module_disabled');
$settings=R::settings();$settings['features']=array('native_oauth'=>true,'remote_mcp'=>true,'project_gateways'=>true);R::save($settings);
$assert(R::server_enabled($server)&&R::server_enabled($manager->get($gateway['id'])),'module_reenable_restores_availability');
$assert($manager->get($remote['id'])->outbound_auth_credentials===$credentials,'disable_enable_preserves_encrypted_credentials');
$after=$wpdb->get_results("SELECT id,auth_config,outbound_auth_credentials,settings,status FROM {$wpdb->prefix}getmcp_servers WHERE id<{$remote['id']} ORDER BY id",ARRAY_A);
$assert($before===$after,'switches_leave_existing_server_configuration_byte_unchanged');
wp_set_current_user(2);$request=new WP_REST_Request('PUT','/getmcp-extensions/v1/settings');$request->set_header('Content-Type','application/json');$request->set_body(wp_json_encode(R::settings()));$assert(rest_do_request($request)->get_status()===403,'subscriber_cannot_change_modules');wp_set_current_user(1);
echo wp_json_encode(array('passed'=>count($checks),'checks'=>$checks,'fixture'=>array('remote_id'=>$remote['id'],'gateway_id'=>$gateway['id'],'remote_url'=>$remote['url'],'gateway_url'=>$gateway['url'])),JSON_PRETTY_PRINT);
