<?php
/** Additional account discovery, import, failure and management contracts. Synthetic HTTP only. */
use GetMCPExtensions\ProviderConnections as PC;
use GetMCPExtensions\ProviderDiscovery as PD;
use GetMCPExtensions\ProviderReadiness as Ready;
use GetMCPExtensions\ConfigurationImport as Importer;
use GetMCPExtensions\AuthenticationSettings as Settings;
global $wpdb;
$f = get_option( 'getmcp_marketing_browser_fixtures' ); $m = new GetMCP\Core\ServerManager(); $tm = new GetMCP\Core\ToolManager(); $a = $f['users'][0]; $checks = array();
$assert = function( $v, $n ) use ( &$checks ) { $checks[$n] = (bool) $v; if ( ! $v ) { throw new RuntimeException( 'FAIL: ' . $n ); } };
$reject = function( $fn, $n ) use ( $assert ) { try { $fn(); } catch ( Throwable $e ) { $assert( true, $n ); return; } $assert( false, $n ); };
$flow = function( $s ) use ( $a ) { $q = array(); wp_parse_str( wp_parse_url( PC::begin( $s, $a )['authorization_url'], PHP_URL_QUERY ), $q ); PC::complete( array( 'state' => $q['state'], 'code' => 'fixture-code-a' ), $a ); return PC::grant( $s, $a ); };
update_option( 'getmcp_fixture_provider_mode', 'valid' );
$s = $m->get( $f['google']['google-ads']['id'] );
$tool = $tm->create( array( 'server_id' => $s->id, 'name' => 'fixture_list_accessible_customers', 'endpoint_url' => 'https://googleads.googleapis.com/v99/customers:listAccessibleCustomers', 'http_method' => 'GET' ) );
$changed = Settings::prepare( $s, array( 'auth_config' => array( 'token_url' => 'https://graph.facebook.com/v26.0/oauth/access_token' ), 'auth_credentials' => array() ) );
$assert( array_key_exists( 'auth_credentials', $changed ) && null === $changed['auth_credentials'], 'provider_host_switch_clears_obsolete_secret' );
$grant = $flow( $s ); $found = PD::discover( $s, $grant['data']['access_token'], $a );
$assert( $found['complete'] && count( $found['customers'] ) === 2 && ! $found['reporting_verified'], 'ads_manager_and_child_discovery_separate_from_reporting' ); $tm->delete( $tool->id );
$s = $m->get( $f['google']['google-search-console']['id'] ); $grant = $flow( $s );
$assert( PD::discover( $s, $grant['data']['access_token'], $a )['properties'][0]['permissionLevel'] === 'siteOwner', 'search_console_property_permission_preserved' );
$status = Ready::connection( $s, $grant['data'], true, array() );
$assert( $status['required_scopes_present'] === false && ! $status['reporting_verified'], 'readiness_reports_missing_scopes_without_inventing_access' );
update_option( 'getmcp_fixture_provider_mode', 'timeout' ); $reject( fn() => PD::discover( $s, $grant['data']['access_token'], $a ), 'provider_read_timeout_reported' );
update_option( 'getmcp_fixture_provider_mode', 'malformed' ); $reject( fn() => PD::discover( $s, $grant['data']['access_token'], $a ), 'malformed_discovery_rejected' ); update_option( 'getmcp_fixture_provider_mode', 'valid' );
$mapped = Importer::map( 'fixture', array( 'url' => 'https://example.org/getmcp-qa/json', 'auth' => array( 'type' => 'oauth2', 'clientId' => 'fixture-client', 'scopes' => 'fixture:read' ) ) );
$assert( $mapped['remote']['scope'] === 'fixture:read' && $mapped['remote']['client_id'] === 'fixture-client', 'nested_oauth_aliases_and_text_scopes_mapped' );
$mapped = Importer::map( 'fixture', array( 'url' => 'https://example.org/getmcp-qa/json', 'oauth' => array( 'scopes' => array( 'read', 'write' ) ) ) );
$assert( $mapped['remote']['scope'] === 'read write', 'array_oauth_scopes_mapped' );
$accounts = Ready::accounts( array( 'ad_entities' => array( array( 'id' => 'fixture-restricted', 'is_ads_mcp_enabled' => false, 'is_queryable' => false, 'reason' => 'Fixture account closed' ), array( 'id' => 'fixture-unknown', 'is_queryable' => true ) ) ) );
$assert( $accounts[0]['is_ads_mcp_enabled'] === false && $accounts[0]['reasons']['reason'] === 'Fixture account closed' && null === $accounts[1]['is_ads_mcp_enabled'] && ! $accounts[1]['reporting_verified'], 'meta_eligibility_queryability_reasons_and_unknowns_preserved' );
$state = array(); wp_parse_str( wp_parse_url( PC::begin( $s, $a )['authorization_url'], PHP_URL_QUERY ), $state );
$original = Settings::object( $s->auth_config ); $m->update( $s->id, array( 'auth_config' => array( 'scope' => 'fixture:changed' ) ) );
$reject( fn() => PC::complete( array( 'state' => $state['state'], 'code' => 'fixture-code-a' ), $a ), 'configuration_change_during_consent_rejected' );
$m->update( $s->id, array( 'auth_config' => $original, '_auth_config_mode' => 'replace' ) );
wp_set_current_user( 1 ); $t = $tm->create( array( 'server_id' => $s->id, 'name' => 'fixture_management_contract', 'endpoint_url' => 'https://example.org/getmcp-qa/json' ) );
$request = new WP_REST_Request( 'GET', '/getmcp/v1/provider-tools/' . $t->id ); $public = rest_do_request( $request )->get_data();
$put = new WP_REST_Request( 'PUT', '/getmcp/v1/provider-tools/' . $t->id ); $put->set_header( 'Content-Type', 'application/json' ); $put->set_body( wp_json_encode( array( 'revision' => $public['revision'], 'body_template' => array( 'fixture' => true ), 'annotations' => array( 'readOnlyHint' => true ), 'retry_count' => 1, 'retry_backoff' => 'linear' ) ) );
$saved = rest_do_request( $put ); $assert( $saved->get_status() === 200 && Settings::object( $tm->get( $t->id )->annotations )['readOnlyHint'], 'management_tool_fields_saved_through_validated_rest' );
$assert( rest_do_request( $put )->get_status() === 409, 'tool_configuration_stale_update_rejected' ); $tm->delete( $t->id );
file_put_contents( '/evidence/discovery.json', wp_json_encode( array( 'passed' => count( $checks ), 'checks' => $checks, 'live_provider_writes' => false ), JSON_PRETTY_PRINT ) );
echo wp_json_encode( array( 'passed' => count( $checks ), 'checks' => $checks ) );
