<?php
/** wp eval-file: real WordPress/database, synthetic provider HTTP. No customer/provider data. */
use GetMCPExtensions\AuthenticationSettings as AuthSettings;
use GetMCPExtensions\ProviderConnections as PC;
use GetMCPExtensions\ProviderTokens as PT;
use GetMCPExtensions\PageTokens as Pages;
use GetMCPExtensions\ProtocolEnvelope as PE;
use GetMCPExtensions\ConfigurationImport as Importer;
use GetMCP\Core\ServerManager as SM;
use GetMCP\Gateway\FeatureManager as FM;
use GetMCP\Remote\UpstreamConnections as UC;
use GetMCP\Utils\Encryption as Enc;

global $wpdb;
$checks = array();
$assert = function( $ok, $name ) use ( &$checks ) { $checks[$name] = (bool) $ok; if ( ! $ok ) { throw new RuntimeException( 'FAIL: ' . $name ); } };
$reject = function( callable $fn, $name ) use ( $assert ) { try { $fn(); } catch ( Throwable $e ) { $assert( true, $name ); return; } $assert( false, $name ); };
$rest = function( $method, $path, $data = null ) { $r = new WP_REST_Request( $method, '/getmcp/v1/' . $path ); if ( null !== $data ) { $r->set_header( 'content-type', 'application/json' ); $r->set_body( wp_json_encode( $data ) ); } return rest_do_request( $r ); };
wp_set_current_user( 1 ); update_option( 'getmcp_fixture_provider_mode', 'valid' );
$a = (int) ( username_exists( 'marketing-a' ) ?: wp_create_user( 'marketing-a', 'disposable-fixture-only', 'marketing-a@example.invalid' ) );
$b = (int) ( username_exists( 'marketing-b' ) ?: wp_create_user( 'marketing-b', 'disposable-fixture-only', 'marketing-b@example.invalid' ) );
$sm = new SM();
foreach ( get_option( 'getmcp_marketing_fixture_ids', array() ) as $id ) { $s = $sm->get( $id ); if ( $s && str_starts_with( $s->name, 'Marketing Fixture ' ) ) { $sm->delete( $id ); } }
$ids = array(); $remember = function( $s ) use ( &$ids ) { $ids[] = $s->id; update_option( 'getmcp_marketing_fixture_ids', $ids ); return $s; };
$assert( GetMCPExtensions\Runtime::status()['profile'] === 'vendor-original-1.6.0', 'genuine_vendor_profile_verified' );
$baseline = AuthSettings::object( get_option( 'getmcp_settings', array() ) );
$google = array();
foreach ( array( 'google-ads', 'google-analytics', 'google-search-console' ) as $preset ) {
    $config = GetMCPExtensions\ProviderDiscovery::presets()[$preset]['auth_config'] + array( 'client_id' => 'fixture-google-application' );
    $s = $remember( $sm->create( array( 'name' => 'Marketing Fixture ' . $preset, 'slug' => 'fixture-' . $preset, 'auth_type' => 'oauth', 'auth_config' => wp_json_encode( $config ), 'auth_credentials' => wp_json_encode( array( 'client_secret' => 'fixture-application-secret' ) ), 'settings' => wp_json_encode( array( 'personal_provider' => array( 'allowed_user_ids' => array( $a, $b ), 'preset' => $preset ) ) ) ) ) );
    $old = $s->auth_credentials; $minimal = array_diff_key( $config, array( 'extra_authorize_params' => true ) );
    $r = $rest( 'PATCH', 'servers/' . $s->uuid, array( 'auth_type' => 'oauth', 'auth_config' => $minimal, 'auth_credentials' => array( 'client_secret' => '' ), 'authentication_revision' => AuthSettings::revision( $s ) ) );
    if ( $r->get_status() !== 200 ) { echo wp_json_encode( array( 'response' => $r->get_data(), 'uuid' => $s->uuid, 'routes' => array_values( array_filter( array_keys( rest_get_server()->get_routes() ), fn( $r ) => str_contains( $r, 'getmcp/v1/servers' ) ) ) ) ); }
    $assert( $r->get_status() === 200, $preset . '_normal_save_accepted' );
    $s = $sm->get( $s->id ); $assert( $s->auth_credentials === $old, $preset . '_encrypted_secret_hash_preserved' );
    $assert( AuthSettings::object( $s->auth_config )['extra_authorize_params'] === $config['extra_authorize_params'], $preset . '_offline_consent_parameters_preserved' );
    $creds = $rest( 'GET', 'servers/' . $s->uuid . '/credentials' )->get_data();
    $assert( null === $creds['auth_credentials'] && $creds['has_auth_credentials'] && ! str_contains( wp_json_encode( $creds ), 'fixture-application-secret' ), $preset . '_credential_endpoint_presence_only' );
    $google[$preset] = $s;
}
$s = $google['google-analytics']; $stale = AuthSettings::revision( $s );
$sm->update( $s->id, array( 'auth_config' => array( 'extra_authorize_params' => array( 'prompt' => 'select_account' ) ) ) );
$r = $rest( 'PATCH', 'servers/' . $s->uuid, array( 'auth_config' => array( 'scope' => 'stale' ), 'authentication_revision' => $stale ) );
$assert( $r->get_status() === 409, 'stale_authentication_save_rejected' );
$s = $sm->get( $s->id ); $old = $s->auth_credentials;
$r = $rest( 'PATCH', 'servers/' . $s->uuid, array( 'auth_config' => array( 'client_secret' => 'must-not-be-plaintext' ), 'authentication_revision' => AuthSettings::revision( $s ) ) );
$assert( $r->get_status() === 400 && $sm->get( $s->id )->auth_credentials === $old, 'unencrypted_config_secret_rejected_without_write' );
$sm->update( $s->id, array( 'auth_config' => array( 'extra_authorize_params' => array( 'prompt' => null ) ) ) );
$assert( ! isset( AuthSettings::object( $sm->get( $s->id )->auth_config )['extra_authorize_params']['prompt'] ), 'explicit_parameter_clear' );
$sm->update( $s->id, array( 'auth_config' => array( 'provider' => 'external', 'client_id' => 'fixture-google-application', 'token_url' => 'https://oauth2.googleapis.com/token', 'authorize_url' => 'https://accounts.google.com/o/oauth2/v2/auth', 'scope' => 'https://www.googleapis.com/auth/analytics.readonly' ), '_auth_config_mode' => 'replace' ) );
$assert( ! isset( AuthSettings::object( $sm->get( $s->id )->auth_config )['extra_authorize_params'] ), 'explicit_full_replacement' );
$sm->update( $s->id, array( '_clear_credentials' => array( 'auth_credentials' ) ) );
$assert( null === $sm->get( $s->id )->auth_credentials, 'explicit_secret_clear' );
$sm->update( $s->id, array( 'auth_credentials' => wp_json_encode( array( 'client_secret' => 'fixture-application-secret' ) ) ) );
$meta = $remember( $sm->create( array( 'name' => 'Marketing Fixture Instagram', 'slug' => 'fixture-instagram', 'auth_type' => 'oauth', 'auth_config' => wp_json_encode( array( 'provider' => 'external', 'authorize_url' => 'https://www.facebook.com/v26.0/dialog/oauth', 'token_url' => 'https://graph.facebook.com/v26.0/oauth/access_token', 'client_id' => 'fixture-meta-application', 'scope' => 'instagram_basic,instagram_manage_messages,pages_manage_metadata' ) ), 'auth_credentials' => wp_json_encode( array( 'client_secret' => 'fixture-meta-secret' ) ), 'settings' => wp_json_encode( array( 'personal_provider' => array( 'allowed_user_ids' => array( $a, $b ), 'preset' => 'instagram-facebook-login' ) ) ) ) ) );
$assert( ! PC::can_connect( $meta, 1 ), 'excluded_administrator_has_no_personal_bypass' );
$flow = function( $s, $user, $who ) {
    $url = PC::begin( $s, $user )['authorization_url']; $q = array(); wp_parse_str( wp_parse_url( $url, PHP_URL_QUERY ), $q );
    PC::complete( array( 'state' => $q['state'], 'code' => 'fixture-code-' . $who ), $user ); return $q;
};
$q = $flow( $meta, $a, 'a' ); $flow( $meta, $b, 'b' );
$assert( PC::grant( $meta, $a )['data']['access_token'] !== PC::grant( $meta, $b )['data']['access_token'], 'two_provider_accounts_isolated' );
$assert( PC::grant( $meta, $a )['data']['expires_at'] > time() + 86400, 'meta_exchange_uses_provider_lifetime' );
$assert( $q['redirect_uri'] === $meta->get_endpoint_url() . '/oauth/callback' && $q['code_challenge_method'] === 'S256', 'existing_callback_and_pkce_preserved' );
$reject( fn() => PC::complete( array( 'state' => $q['state'], 'code' => 'fixture-code-a' ), $a ), 'callback_replay_rejected' );
$url = PC::begin( $meta, $a )['authorization_url']; $pending = array(); wp_parse_str( wp_parse_url( $url, PHP_URL_QUERY ), $pending );
$reject( fn() => PC::complete( array( 'state' => $pending['state'], 'code' => 'fixture-code-a' ), $b ), 'wrong_browser_user_rejected' );
UC::disconnect( $meta->id, $a );
$reject( fn() => PC::complete( array( 'state' => $pending['state'], 'code' => 'fixture-code-a' ), $a ), 'disconnect_during_consent_cannot_resurrect' );
$flow( $meta, $a, 'a' ); $ga = PC::grant( $meta, $a ); $gb = PC::grant( $meta, $b );
$pa = Pages::discover( $meta, 'user:' . $a, $ga['data']['access_token'] ); $pb = Pages::discover( $meta, 'user:' . $b, $gb['data']['access_token'] );
$assert( count( $pa['pages'] ) === 2 && $pa['discovery_complete'], 'complete_page_pagination_without_following_next_url' );
$assert( ! str_contains( wp_json_encode( $pa ), 'fixture-page-' ), 'page_picker_never_returns_tokens' );
$reject( fn() => Pages::select( $meta, 'user:' . $a, $ga['data']['access_token'], '201', '1201' ), 'another_users_page_rejected' );
$reject( fn() => Pages::select( $meta, 'user:' . $a, $ga['data']['access_token'], '101', '1102' ), 'mismatched_instagram_page_pair_rejected' );
Pages::select( $meta, 'user:' . $a, $ga['data']['access_token'], '101', '1101' );
$reject( fn() => Pages::token( $meta, 'user:' . $a, $ga['data']['access_token'], array( 'page_id' => '101' ) ), 'messaging_requires_harmless_read' );
Pages::verify( $meta, 'user:' . $a, $ga['data']['access_token'] );
$assert( Pages::token( $meta, 'user:' . $a, $ga['data']['access_token'], array( 'page_id' => '101' ) ) === 'fixture-page-a-101', 'selected_user_page_token_used' );
$reject( fn() => Pages::token( $meta, 'user:' . $a, $ga['data']['access_token'], array( 'page_id' => '102' ) ), 'unselected_page_rejected' );
$reject( fn() => Pages::token( $meta, 'user:' . $a, $ga['data']['access_token'], array( 'conversation_id' => 'conversation-b' ) ), 'cross_page_conversation_rejected' );
Pages::select( $meta, 'user:' . $a, $ga['data']['access_token'], '102', '1102' );
$reject( fn() => Pages::token( $meta, 'user:' . $a, $ga['data']['access_token'], array() ), 'selection_change_invalidates_messaging_readiness' );
Pages::verify( $meta, 'user:' . $a, $ga['data']['access_token'] );
$assert( Pages::token( $meta, 'user:' . $a, $ga['data']['access_token'], array( 'page_id' => '102' ) ) === 'fixture-page-a-102', 'page_switch_selects_new_token' );
update_option( 'getmcp_fixture_provider_mode', 'denied_scopes' ); Pages::discover( $meta, 'user:' . $a, $ga['data']['access_token'] ); Pages::select( $meta, 'user:' . $a, $ga['data']['access_token'], '101', '1101' );
$reject( fn() => Pages::verify( $meta, 'user:' . $a, $ga['data']['access_token'] ), 'denied_messaging_scopes_rejected' );
update_option( 'getmcp_fixture_provider_mode', 'valid' ); Pages::discover( $meta, 'user:' . $a, $ga['data']['access_token'] ); Pages::select( $meta, 'user:' . $a, $ga['data']['access_token'], '101', '1101' ); Pages::verify( $meta, 'user:' . $a, $ga['data']['access_token'] );
update_option( 'getmcp_fixture_provider_mode', 'revoke' );
$reject( fn() => Pages::verify( $meta, 'user:' . $a, $ga['data']['access_token'] ), 'revoked_page_token_read_fails' );
update_option( 'getmcp_fixture_provider_mode', 'valid' );
$expired = $ga['data']; $expired['expires_at'] = time() - 1; UC::save( $meta->id, $a, $expired, $ga['version'] );
$reject( fn() => PC::grant( $meta, $a ), 'expired_meta_requires_reconnect_not_refresh_grant' );
$flow( $meta, $a, 'a' ); $ga = PC::grant( $meta, $a );
$reject( fn() => Pages::token( $meta, 'user:' . $a, $ga['data']['access_token'], array() ), 'reconnect_invalidates_old_page_selection' );
$s = $sm->get( $google['google-analytics']->id ); $flow( $s, $a, 'a' ); $g = PC::grant( $s, $a ); $d = $g['data']; $d['expires_at'] = time() - 1; UC::save( $s->id, $a, $d, $g['version'] );
$assert( PC::grant( $s, $a )['data']['expires_at'] > time(), 'google_refresh_grant_preserved' );
$assert( count( GetMCPExtensions\ProviderDiscovery::discover( $s, PC::grant( $s, $a )['data']['access_token'], $a )['accounts'] ) === 2, 'analytics_account_summary_pagination' );
$g1 = FM::run( 'save', array( 'kind' => 'gateway', 'name' => 'Marketing Fixture Gateway A', 'allowed_user_ids' => array( $a ), 'server_ids' => array( $meta->id ) ) ); $remember( $sm->get( $g1['id'] ) );
$g2 = FM::run( 'save', array( 'kind' => 'gateway', 'name' => 'Marketing Fixture Gateway B', 'allowed_user_ids' => array( $b ), 'server_ids' => array( $s->id ) ) ); $remember( $sm->get( $g2['id'] ) );
$settings = AuthSettings::object( $meta->settings ); $settings['personal_provider']['allowed_user_ids'] = array(); $sm->update( $meta->id, array( 'settings' => wp_json_encode( $settings ) ) ); $meta = $sm->get( $meta->id );
$assert( PC::can_connect( $meta, $a ) && ! PC::can_connect( $meta, $b ) && ! PC::can_connect( $meta, 1 ), 'gateway_delegates_without_direct_access_or_admin_bypass' );
FM::run( 'save', array( 'id' => $g1['id'], 'server_ids' => array() ) );
$reject( fn() => PC::grant( $meta, $a ), 'removed_gateway_membership_immediately_denies_provider_use' );
$settings['personal_provider']['allowed_user_ids'] = array( $a, $b ); $sm->update( $meta->id, array( 'settings' => wp_json_encode( $settings ) ) ); $meta = $sm->get( $meta->id );
$sm->update( $meta->id, array( 'status' => 'paused' ) );
$reject( fn() => PC::grant( $sm->get( $meta->id ), $a ), 'paused_server_immediately_denies_provider_use' ); $sm->update( $meta->id, array( 'status' => 'active' ) );
$rpc = array( 'jsonrpc' => '2.0', 'id' => 1, 'result' => array( 'content' => array( array( 'type' => 'text', 'text' => 'fixture result' ) ), 'structuredContent' => array( 'ad_entities' => '[{"id":"fixture-ad"}]' ) ) );
$decoded = PE::decode( 'event: message' . "\n" . 'data: ' . wp_json_encode( $rpc ) . "\n\n" );
$assert( $decoded['structuredContent']['ad_entities'][0]['id'] === 'fixture-ad', 'meta_sse_and_json_string_structured_data_normalized' );
$nested = array( 'content' => array( array( 'type' => 'text', 'text' => wp_json_encode( $rpc ) ) ) );
$assert( PE::decode( wp_json_encode( $nested ) )['content'][0]['text'] === 'fixture result', 'nested_mcp_json_rpc_unwrapped' );
$assert( PE::decode( '{"jsonrpc":"2.0","id":1,"error":{"code":-1,"message":"private"}}' )['isError'], 'json_rpc_error_not_http_success' );
$reject( fn() => PE::decode( "data: {invalid}\n\n" ), 'malformed_sse_rejected' );
$reject( fn() => PE::decode( str_repeat( 'x', 10485761 ) ), 'oversized_envelope_rejected' );
$preview = Importer::preview( '{"mcpServers":{"Fixture Imported":{"url":"https://example.org/getmcp-qa/json","headers":{"Authorization":"Bearer fixture-import-secret","X-Project":"fixture-header-secret"}}}}', 1 );
$assert( ! str_contains( wp_json_encode( $preview ), 'fixture-import-secret' ) && $preview['entries'][0]['remote']['auth_mode'] === 'shared', 'import_preview_maps_but_never_returns_secrets' );
$reject( fn() => Importer::commit( array( 'preview_token' => $preview['preview_token'], 'index' => 0 ), $a ), 'import_confirmation_other_user_denied' );
$imported = Importer::commit( array( 'preview_token' => $preview['preview_token'], 'index' => 0, 'configuration' => array( 'name' => 'Marketing Fixture Imported', 'allowed_user_ids' => array( 1 ) ) ), 1 ); $remember( $sm->get( $imported['id'] ) );
$assert( ! str_contains( $sm->get( $imported['id'] )->outbound_auth_credentials, 'fixture-import-secret' ), 'imported_credentials_encrypted' );
$reject( fn() => Importer::commit( array( 'preview_token' => $preview['preview_token'], 'index' => 0 ), 1 ), 'import_preview_single_use' );
foreach ( array( "[mcp_servers.example]\nurl = \"https://example.org/getmcp-qa/json\"\n[mcp_servers.example.http_headers]\nX-Project = \"fixture\"", "mcpServers:\n  example:\n    url: https://example.org/getmcp-qa/json\n    headers:\n      X-Project: fixture", 'claude mcp add --transport http example https://example.org/getmcp-qa/json', 'https://example.org/getmcp-qa/json' ) as $i => $text ) { $mapped = Importer::map( 'fixture', array_values( Importer::parse( $text ) )[0] ); $assert( $mapped['supported'], 'transcoder_format_' . $i ); }
$assert( ! Importer::map( 'command', array( 'command' => 'python', 'args' => array( 'server.py' ) ) )['supported'], 'command_only_import_requires_reviewed_port' );
$reject( fn() => Importer::map( 'private', array( 'url' => 'https://127.0.0.1/mcp' ) ), 'import_ssrf_endpoint_rejected' );
$remote = FM::run( 'save', array( 'kind' => 'remote-mcp', 'name' => 'Marketing Fixture Headers', 'allowed_user_ids' => array( 1 ), 'remote' => array( 'endpoint' => 'https://example.org/getmcp-qa/json', 'auth_mode' => 'none' ), 'connection_headers' => array( array( 'name' => 'X-Project', 'value' => 'fixture-header-secret' ) ) ) ); $remember( $sm->get( $remote['id'] ) );
$assert( UC::headers( $sm->get( $remote['id'] ), 1 )['X-Project'] === 'fixture-header-secret', 'custom_headers_work_without_authentication' );
$saved = FM::run( 'save', array( 'id' => $remote['id'], 'connection_headers' => array( array( 'name' => 'X-Project', 'value' => '' ) ) ) );
$assert( UC::headers( $sm->get( $remote['id'] ), 1 )['X-Project'] === 'fixture-header-secret' && ! str_contains( wp_json_encode( $saved ), 'fixture-header-secret' ), 'blank_header_save_preserves_secret_without_export' );
$reject( fn() => FM::run( 'save', array( 'id' => $remote['id'], 'connection_headers' => array( array( 'name' => 'Authorization', 'value' => 'stolen' ) ) ) ), 'custom_headers_cannot_override_personal_auth' );
$tool = new GetMCP\Core\Tool( array( 'id' => 999, 'slug' => 'graph_fields', 'endpoint_url' => 'https://graph.facebook.com/v26.0/{{page_id}}?fields=id,instagram_business_account{username}', 'http_method' => 'GET', 'input_schema' => '{"type":"object","properties":{"page_id":{"type":"string"}}}' ) );
$request = ( new GetMCP\Execution\ParameterResolver() )->resolve( $tool, array( 'page_id' => '101' ) );
$assert( str_contains( rawurldecode( $request['url'] ), 'instagram_business_account{username}' ) && str_contains( $request['url'], '/101?' ), 'graph_static_nested_fields_survive_argument_resolution' );
update_option( 'getmcp_marketing_browser_fixtures', array( 'google' => array_map( fn( $s ) => array( 'id' => $s->id, 'uuid' => $s->uuid ), $google ), 'instagram' => array( 'id' => $meta->id, 'uuid' => $meta->uuid ), 'users' => array( $a, $b ) ) );
$assert( get_option( 'getmcp_settings', array() ) === $baseline, 'unrelated_vendor_settings_preserved' );
file_put_contents( '/evidence/wordpress.json', wp_json_encode( array( 'passed' => count( $checks ), 'checks' => $checks, 'environment' => array( 'wordpress' => get_bloginfo( 'version' ), 'php' => PHP_VERSION, 'database' => $wpdb->db_version(), 'provider_http' => 'synthetic' ), 'live_provider_writes' => false ), JSON_PRETTY_PRINT ) );
echo wp_json_encode( array( 'passed' => count( $checks ), 'checks' => $checks ) );
